apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-ahana
  labels:
    app: hotel-ahana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-ahana
  template:
    metadata:
      labels:
        app: hotel-ahana
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: hotel-ahana
        image: 9900772083/hotel-ahana:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
